# This ini file is needed by XV2 Mods Installer to track the skill.
# DON'T DELETE IT OR SKILL WILL BE UNABLE TO BE UNINSTALLED OR PROPERLY UPDATED

[General]
GUID = "c099b7ff-1f13-2d27-02ba-5ce7e8faeef2"