# This ini file is needed by XV2 Mods Installer to track the skill.
# DON'T DELETE IT OR SKILL WILL BE UNABLE TO BE UNINSTALLED OR PROPERLY UPDATED

[General]
GUID = "06bab598-a949-2763-27c3-2afa5625fb91"