# This ini file is needed by XV2 Mods Installer to track the skill.
# DON'T DELETE IT OR SKILL WILL BE UNABLE TO BE UNINSTALLED OR PROPERLY UPDATED

[General]
GUID = "76795cc3-faf2-20f3-507f-d19c2f1eb039"
PUP = "0x9e,0x9f,0xa0,0xa1,0xa2,0xa3,0xa4,0xa5,0xa6,0xa7"
CUS_AUR = "0x4e,0x4f,0x50,0x51,0x52,0x53,0x54,0x55,0x56,0x57"