# This ini file is needed by XV2 Mods Installer to track the skill.
# DON'T DELETE IT OR SKILL WILL BE UNABLE TO BE UNINSTALLED OR PROPERLY UPDATED

[General]
GUID = "ea45572d-43bb-2a8c-1124-f3f0dd0e2eb7"
PUP = "0x94,0x95,0x96,0x97,0x98,0x99,0x9a,0x9b,0x9c,0x9d"
CUS_AUR = "0x44,0x45,0x46,0x47,0x48,0x49,0x4a,0x4b,0x4c,0x4d"