# This ini file is needed by XV2 Mods Installer to track the skill.
# DON'T DELETE IT OR SKILL WILL BE UNABLE TO BE UNINSTALLED OR PROPERLY UPDATED

[General]
GUID = "94b99b13-2f10-e7ad-cadb-e29de90eea4d"